cask 'font-prog-office-code-pro-nerd-font' do
  version "001.004"
  sha256 "34654980793ce2a0579caf386d95543349460fdadbb22057fc64a16435cf024a"

  url "https://#{ENV['HOMEBREW_GITHUB_API_TOKEN']}@raw.githubusercontent.com/alejakun/homebrew-cask-assets/master/Fonts/Programming/office-code-pro.zip"
  name "OfficeCodePro Nerd Font"
  homepage "https://github.com/nathco/Office-Code-Pro"

  font "office-code-pro/Office Code Pro Bold Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Bold Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Bold Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Bold Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Light Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Light Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Medium Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Medium Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Regular Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro D Regular Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Light Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Light Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Medium Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Medium Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Regular Italic Nerd Font Complete.otf"
  font "office-code-pro/Office Code Pro Regular Nerd Font Complete.otf"
end
