cask 'font-prog-input-sans-nerd-font' do
  version "0.000"
  sha256 "7e96323b03b26c8de6826abcb9d96e87077f0111dbef2cc7d5feb0773d749624"

  url "https://#{ENV['HOMEBREW_GITHUB_API_TOKEN']}@raw.githubusercontent.com/alejakun/homebrew-cask-assets/master/Fonts/Programming/input-sans.zip"
  name "InputSans Nerd Font"
  homepage "https://input.djr.com"

  font "input-sans/InputSans Black Nerd Font Complete.ttf"
  font "input-sans/InputSans BlackIta Nerd Font Complete.ttf"
  font "input-sans/InputSans Bold Nerd Font Complete.ttf"
  font "input-sans/InputSans BoldIta Nerd Font Complete.ttf"
  font "input-sans/InputSans ExLight Nerd Font Complete.ttf"
  font "input-sans/InputSans ExLightIta Nerd Font Complete.ttf"
  font "input-sans/InputSans Italic Nerd Font Complete.ttf"
  font "input-sans/InputSans Light Nerd Font Complete.ttf"
  font "input-sans/InputSans LightIta Nerd Font Complete.ttf"
  font "input-sans/InputSans Medium Nerd Font Complete.ttf"
  font "input-sans/InputSans MediumIta Nerd Font Complete.ttf"
  font "input-sans/InputSans Nerd Font Complete.ttf"
  font "input-sans/InputSans Thin Nerd Font Complete.ttf"
  font "input-sans/InputSans ThinIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Black Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed BlackIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Bold Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed BoldIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed ExLight Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed ExLightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Italic Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Light Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed LightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Medium Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed MediumIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed Thin Nerd Font Complete.ttf"
  font "input-sans/InputSansCompressed ThinIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Black Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed BlackIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Bold Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed BoldIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed ExLight Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed ExLightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Italic Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Light Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed LightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Medium Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed MediumIta Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed Thin Nerd Font Complete.ttf"
  font "input-sans/InputSansCondensed ThinIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Black Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow BlackIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Bold Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow BoldIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow ExLight Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow ExLightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Italic Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Light Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow LightIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Medium Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow MediumIta Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow Thin Nerd Font Complete.ttf"
  font "input-sans/InputSansNarrow ThinIta Nerd Font Complete.ttf"
end
