cask 'font-benton-sans' do
  version "1.000"
  sha256 "a7c481dda4be16203f578abb97bf790180aa658e2ed39f85e62cdb423ad50c5d"

  url "https://#{ENV['HOMEBREW_GITHUB_API_TOKEN']}@raw.githubusercontent.com/alejakun/homebrew-cask-assets/master/Fonts/General/benton-sans.zip"
  name "BentonSans"
  homepage "https://www.fontreach.com/benton-sans-font-free-download/"

  font "Benton-Sans/BentonSans Black.otf"
  font "Benton-Sans/BentonSans Bold.otf"
  font "Benton-Sans/BentonSans Book.otf"
  font "Benton-Sans/BentonSans Comp Black.otf"
  font "Benton-Sans/BentonSans Comp Bold.otf"
  font "Benton-Sans/BentonSans Comp Book.otf"
  font "Benton-Sans/BentonSans Comp Light.otf"
  font "Benton-Sans/BentonSans Comp Medium.otf"
  font "Benton-Sans/BentonSans Comp Regular.otf"
  font "Benton-Sans/BentonSans Cond Black.otf"
  font "Benton-Sans/BentonSans Cond Bold.otf"
  font "Benton-Sans/BentonSans Cond Book.otf"
  font "Benton-Sans/BentonSans Cond Light.otf"
  font "Benton-Sans/BentonSans Cond Medium.otf"
  font "Benton-Sans/BentonSans Cond Regular.otf"
  font "Benton-Sans/BentonSans ExtraComp Black.otf"
  font "Benton-Sans/BentonSans ExtraComp Bold.otf"
  font "Benton-Sans/BentonSans ExtraComp Book.otf"
  font "Benton-Sans/BentonSans ExtraComp Light.otf"
  font "Benton-Sans/BentonSans ExtraComp Medium.otf"
  font "Benton-Sans/BentonSans ExtraComp Regular.otf"
  font "Benton-Sans/BentonSans ExtraLight.otf"
  font "Benton-Sans/BentonSans Light.otf"
  font "Benton-Sans/BentonSans Medium.otf"
  font "Benton-Sans/BentonSans Regular.otf"
  font "Benton-Sans/BentonSans Thin.otf"
end
