cask 'programming-font-input-mono' do
  version "0.000"
  sha256 "19a6a61356e1503c40b94bbf4323c6bc7083fbe249686df76759e4ba1e65e1b3"

  url "https://#{ENV['HOMEBREW_GITHUB_API_TOKEN']}@raw.githubusercontent.com/alejakun/homebrew-cask-assets/master/Fonts/Programming/input-mono.zip"
  name "InputMono Nerd Font"
  homepage "https://input.djr.com"

  font "input-mono/InputMono Black Nerd Font Complete.ttf"
  font "input-mono/InputMono BlackIta Nerd Font Complete.ttf"
  font "input-mono/InputMono Bold Nerd Font Complete.ttf"
  font "input-mono/InputMono BoldIta Nerd Font Complete.ttf"
  font "input-mono/InputMono ExLight Nerd Font Complete.ttf"
  font "input-mono/InputMono ExLightIta Nerd Font Complete.ttf"
  font "input-mono/InputMono Italic Nerd Font Complete.ttf"
  font "input-mono/InputMono Light Nerd Font Complete.ttf"
  font "input-mono/InputMono LightIta Nerd Font Complete.ttf"
  font "input-mono/InputMono Medium Nerd Font Complete.ttf"
  font "input-mono/InputMono MediumIta Nerd Font Complete.ttf"
  font "input-mono/InputMono Nerd Font Complete.ttf"
  font "input-mono/InputMono Thin Nerd Font Complete.ttf"
  font "input-mono/InputMono ThinIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Black Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed BlackIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Bold Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed BoldIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed ExLight Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed ExLightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Italic Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Light Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed LightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Medium Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed MediumIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed Thin Nerd Font Complete.ttf"
  font "input-mono/InputMonoCompressed ThinIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Black Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed BlackIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Bold Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed BoldIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed ExLight Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed ExLightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Italic Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Light Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed LightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Medium Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed MediumIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed Thin Nerd Font Complete.ttf"
  font "input-mono/InputMonoCondensed ThinIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Black Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow BlackIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Bold Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow BoldIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow ExLight Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow ExLightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Italic Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Light Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow LightIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Medium Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow MediumIta Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow Thin Nerd Font Complete.ttf"
  font "input-mono/InputMonoNarrow ThinIta Nerd Font Complete.ttf"
end
