cask 'programming-font-input-serif' do
  version "0.000"
  sha256 "3ef2bf682404f62e63d3d1059fbfe67b79b6664ae54943b3e284c99495fdc782"

  url "https://#{ENV['HOMEBREW_GITHUB_API_TOKEN']}@raw.githubusercontent.com/alejakun/homebrew-cask-assets/master/Fonts/Programming/input-serif.zip"
  name "InputSerif Nerd Font"
  homepage "https://input.djr.com"

  font "input-serif/InputSerif Black Nerd Font Complete.ttf"
  font "input-serif/InputSerif BlackIta Nerd Font Complete.ttf"
  font "input-serif/InputSerif Bold Nerd Font Complete.ttf"
  font "input-serif/InputSerif BoldIta Nerd Font Complete.ttf"
  font "input-serif/InputSerif ExLight Nerd Font Complete.ttf"
  font "input-serif/InputSerif ExLightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerif Italic Nerd Font Complete.ttf"
  font "input-serif/InputSerif Light Nerd Font Complete.ttf"
  font "input-serif/InputSerif LightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerif Medium Nerd Font Complete.ttf"
  font "input-serif/InputSerif MediumIta Nerd Font Complete.ttf"
  font "input-serif/InputSerif Nerd Font Complete.ttf"
  font "input-serif/InputSerif Thin Nerd Font Complete.ttf"
  font "input-serif/InputSerif ThinIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Black Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed BlackIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Bold Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed BoldIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed ExLight Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed ExLightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Italic Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Light Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed LightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Medium Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed MediumIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed Thin Nerd Font Complete.ttf"
  font "input-serif/InputSerifCompressed ThinIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Black Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed BlackIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Bold Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed BoldIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed ExLight Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed ExLightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Italic Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Light Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed LightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Medium Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed MediumIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed Thin Nerd Font Complete.ttf"
  font "input-serif/InputSerifCondensed ThinIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Black Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow BlackIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Bold Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow BoldIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow ExLight Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow ExLightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Italic Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Light Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow LightIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Medium Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow MediumIta Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow Thin Nerd Font Complete.ttf"
  font "input-serif/InputSerifNarrow ThinIta Nerd Font Complete.ttf"
end
